# Nen con fig cho bat cu 1 ung dung nao
server:
  port: 8080
  servlet:
    # Khi trong he_thong co nhieu microservice, giup dinh vi microservice va giup co 1 lot balancer giup routing request den dung microservice
    context-path: /identity_service

spring:
  datasource:
    url: "${DB_URL:jdbc:mysql://localhost:3306/identity_service}"
    username: "${DB_USERNAME:root}"
    password: "${DB_PASSWORD:root}"
    driverClassName: "com.mysql.cj.jdbc.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  signerKey: "{SECRET_KEY}"
  valid-duration: 3600  # second
  refreshable-duration: 360000 # second